Lesson 1
galizien/altexsoftlab-bodnarchuk pull request #1
Opened 2021-05-27 13:25 UTC by galizien

Lesson 1

2021-05-30 17:12 UTC, Maxim-Bondar commented on lesson1/assets/dots.svg
> +<svg width="227" height="226" viewBox="0 0 227 226" fill="none" xmlns="http://www.w3.org/2000/svg">
svg must be minified by https://jakearchibald.github.io/svgomg/

2021-05-30 17:14 UTC, Maxim-Bondar commented on lesson1/index.html
> +     <!-- <div class="wholse-content"> -->
remove comment

2021-05-30 17:14 UTC, Maxim-Bondar commented on lesson1/index.html
> +               <img src="assets/logo-nav.png" class="logo" alt="">
attribute `alt` shouldn't be empty

2021-05-30 17:16 UTC, Maxim-Bondar commented on lesson1/index.html
> +               <input id="menu__toggle" type="checkbox" />
css implenetation is not accectable for this task, hamburger menu should be implemented by js

2021-05-30 17:16 UTC, Maxim-Bondar commented on lesson1/index.html
> +
use `.prittier` for code formating

2021-05-30 17:17 UTC, Maxim-Bondar commented on lesson1/index.html
> +               <img src="assets/logo-nav.png" class="laptop-logo" alt="">
logo should be a link

2021-05-30 17:18 UTC, Maxim-Bondar commented on lesson1/index.html
> +                    <div class="header-links">
it should be a navigation list instead of div

2021-05-30 17:19 UTC, Maxim-Bondar commented on lesson1/index.html
> +                    <button class="header-button-first">Get Skout</button>
these buttons has the same style , you don't need classes for each button

2021-05-30 17:20 UTC, Maxim-Bondar commented on lesson1/index.html
> +          <div class="title">Tips & Tools</div>
use title tags instead of div `h1 .... h6`

2021-05-30 17:21 UTC, Maxim-Bondar commented on lesson1/index.html
> +               <div class="vl"></div>
uselles element , it can be implemented by pseudo elements

2021-05-30 17:23 UTC, Maxim-Bondar commented on lesson1/index.html
> +     <section class="content">
here better to use tag `main`

2021-05-30 17:24 UTC, Maxim-Bondar commented on lesson1/index.html
> +          <div class="tips-container">
redundant wrapper

2021-05-30 17:25 UTC, Maxim-Bondar commented on lesson1/index.html
> +                    <div class="line"></div>
useless element, it shoulb be implemented by css

2021-05-30 17:26 UTC, Maxim-Bondar commented on lesson1/index.html
> +                    <div class="did">
class `.did` is not obvious, difficult to understand what this class do

2021-05-30 17:27 UTC, Maxim-Bondar commented on lesson1/index.html
> +                         <img src="assets/skout-tips.svg" alt="skout-tips" class="content-image">
it should be a text instead of image

2021-05-30 17:27 UTC, Maxim-Bondar commented on lesson1/index.html
> +                         <div class="count-line">
uselles element it should be made by css

2021-05-30 17:28 UTC, Maxim-Bondar commented on lesson1/index.html
> +                         <div class="accordain-block">
typo in word accordain

2021-05-30 17:30 UTC, Maxim-Bondar commented on lesson1/index.html
> +                              <a class="accordion">
it semantically not correct to put `div` inside `link`, by the way here you should use `button` with `span` inside

2021-05-30 17:31 UTC, Maxim-Bondar commented on lesson1/index.html
> +                                             <div class="laptop-panel-title">System Patching</div>
use appropriate tags for title istead of div

2021-05-30 17:32 UTC, Maxim-Bondar commented on lesson1/index.html
> +                                   <div class="laptop-panels">
a lot of useless wrappers, please check it can be simplify

2021-05-30 17:33 UTC, Maxim-Bondar commented on lesson1/index.html
> +                                                  <img src="assets/circle.png" width="370px" height="370px" alt="">
image shouldn't be hardcoded inline, it must inheirite parent parent wrapper size

2021-05-30 17:40 UTC, Maxim-Bondar commented on lesson1/index.html
> +                                        <div class="t">IP Address</div>
what class `t` means, we have discussed class names on the last meeting, the class name must be obviously for everyone

2021-05-30 17:41 UTC, Maxim-Bondar commented on lesson1/index.html
> +                                   <div>
it should be a list

2021-05-30 17:42 UTC, Maxim-Bondar commented on lesson1/index.html
> +                                        <div class="slider-title">IP Address</div>
it should be a heading tag

2021-05-30 17:43 UTC, Maxim-Bondar commented on lesson1/index.html
> +                                        <div class="slider-text">Malicious software that blocks access to a system until
it should be a paragraph tag

2021-05-30 17:44 UTC, Maxim-Bondar commented on lesson1/index.html
> +          <div class="faq-container">
for this section the same comments as for accordion above

2021-05-30 17:45 UTC, Maxim-Bondar commented on lesson1/index.html
> +          <div class="footer-links">
should be a list with links inside

2021-05-30 17:45 UTC, Maxim-Bondar commented on lesson1/index.html
> +          <div class="for-line">
useless element

2021-05-30 17:46 UTC, Maxim-Bondar commented on lesson1/index.html
> +               <div class="phone-number">+1 631-203-6600</div>
should be a link with `href="tel:...."`

2021-05-30 17:46 UTC, Maxim-Bondar commented on lesson1/index.html
> +               <div class="socials-links">
should be a list

2021-05-30 17:47 UTC, Maxim-Bondar commented on lesson1/index.html
> +     <footer class="laptop">
you don't need a tons of similar sections, remove useless footer and make changes by css

2021-05-30 17:48 UTC, Maxim-Bondar commented on lesson1/index.html
> +     <!-- <script src="script/stick.js"></script>
remove commented code

2021-05-30 18:05 UTC, Maxim-Bondar requested changes
- remove node_modules from request
- you don't have `scss` styles in your request
- remove all redundant sections, which you created for each section where you must make styles changes by media queries
- hero section must have full width https://prnt.sc/13llt2v
- don't have an underline for selected elements https://prnt.sc/13llu59
- buttons don't have a hover state as was mentioned in technical task https://prnt.sc/13llvzh
- not as is the design https://prnt.sc/13llxlz 
- slider is broken https://prnt.sc/13llylj
- arrow should aligned right https://prnt.sc/13llzun
- footer should have a full width https://prnt.sc/13lm0i1
- broken sections on mobile https://prnt.sc/13lm39a  https://prnt.sc/13lm43o https://prnt.sc/13lm53b

2021-05-31 10:33 UTC, galizien commented on lesson1/assets/dots.svg
> +<svg width="227" height="226" viewBox="0 0 227 226" fill="none" xmlns="http://www.w3.org/2000/svg">
done

2021-05-31 10:34 UTC, galizien commented on lesson1/index.html
> +     <!-- <div class="wholse-content"> -->
removed comment

2021-07-05 07:28 UTC, closed without merging